[package]
name = "particle_physic_sim"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "*", features = ["dynamic"] }
bevy_flycam = "*"
bevy-inspector-egui = "*"
rand = "0.8"
